### ISSUE TITLE
Regex simplification

### ISSUE THREAD

**Issue by Lewiscowles1986** [jordan-miguel/Crazy-Hate-Group#3]
There is a case insensitivity operator you could use for two of the regex's to ensure that merely the combination of i and s characters trigger the replacement.

A slight other side to this issue is that the white-space regex modifier is not used so other whitespace besides a regular space character should not currently be matched, hyphenation is not matched etc.

The last issue is with the word islamic being replaced with non-islamic. If someone like my sister for example noticed the words non-islamic being applied in a clearly islamic context she'd be upset and complain to any publication legitimately using the word islamic. Consider if you will a contrived example

> The islamic celebration of Eid

becomes

> The non-islamic celebration of Eid

depends on the audience absolutely, but perhaps consider combining uses of the word islamic with words like caliphate, jihad, etc.

Whilst we are on the word jihad, perhaps replace the word jihad with something else?

**Comment by jordan-miguel** [comment]
good point.
