### ISSUE TITLE
Google instant-search shows ISIS

### ISSUE THREAD

**Issue by Lewiscowles1986** [jordan-miguel/Crazy-Hate-Group#4]
I believe because google instant-search is using ajax, the event you are using is perhaps being subverted, but the word ISIS clearly still shows. It would be interesting to see a case implemented for replacing the text in AJAX loaded content (like disqus feeds)

**Comment by Lewiscowles1986** [comment]
check out the tiny 3-line fix over at [my fork](https://github.com/Lewiscowles1986/Crazy-Hate-Group/blob/DOMMutation/content.js) :wink: 

``` javascript
document.body.addEventListener('DOMSubtreeModified', function () {
    walk(document.body);
});
```

**Comment by jordan-miguel** [comment]
Thanks a lot! I didn't notice that at first!
